name: Deploy Project
on: push # simple form of push
jobs:
  test: # first job
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3 # although the runner ubuntu-latest has it, however here we are practicing
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy: #  second job after test # jobs run in parllel
    runs-on: ubuntu-latest # every job has a runner
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3 # although the runner ubuntu-latest has it, however here we are practicing
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..." # simulate pushing to server
